# Generated by Django 3.0.2 on 2020-01-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=30)),
                ('CreatedBy', models.CharField(max_length=30)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(db_index=True, max_length=30)),
                ('CreatedBy', models.CharField(db_index=True, max_length=30)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_Product.Category')),
            ],
        ),
    ]
