# Generated by Django 3.0.2 on 2020-01-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_locationid'),
        ('Shop_Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField(blank=True)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_Product.Category')),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
                ('SubCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_Product.SubCategory')),
            ],
        ),
    ]
