# Generated by Django 3.0.2 on 2020-01-23 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_customer_locationid'),
        ('Shop_Product', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField(auto_now=True)),
                ('Quantity', models.PositiveIntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DeliveryCharge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DeliveryStatus', models.CharField(default='Pending', max_length=15)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.location')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_Product.Order')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_Product.Product')),
            ],
        ),
    ]
