# Generated by Django 3.0.2 on 2020-01-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_postalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=120)),
                ('PostalCode', models.PositiveIntegerField()),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.location')),
            ],
        ),
    ]
