# Generated by Django 3.0.2 on 2020-01-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_location_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='LocationId',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='accounts.location'),
            preserve_default=False,
        ),
    ]
