# Generated by Django 3.0.2 on 2020-01-29 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop_Product', '0006_cart_deliverycharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='courierList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courierName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=100)),
                ('CustomerAddress', models.CharField(max_length=100)),
                ('CustomerMobile', models.CharField(max_length=100)),
                ('DeliveryStatus', models.CharField(max_length=100)),
                ('CourierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.courierList')),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_Product.Order')),
            ],
        ),
    ]
